### ISSUE TITLE
 0-Storv2 v0.3 Monitoring Features

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/quantum-storage#13]
# Monitoring Features for 0-Stor-v2 v0.3

0-stor-v2 is one of the  component that makes up the QSFS. It is able to store data in multiple chunks on0-db backends, retrieve, rebuild, restore it on a new 0-db according to the current config. 

Monitoring is one of the required features of the new v0.5 release of QSFS. Monitoring needs to execute checks for  zstor binary failure status, backend health status, and local 0-db space limit status. Certain monitoring requirements need to be met and implemented within 0-stor v2, which will belong to 0-storv2 v0.3 upgrade.

## User Story

(type_story): Monitoring Feature for 0-stor v0.3

#### Tickets (type_feature)
- [x] Add basic statistics to 0-stor monitor daemon [0-storv2 #43](https://github.com/threefoldtech/0-stor_v2/issues/43)
- [x] Monitor 0-db failures and add actions to auto recover [0-storv2 #51](https://github.com/threefoldtech/0-stor_v2/issues/51)
- [x] Enable basic reporting to statistics server(e.g. grafana) [0-storv2 #52](https://github.com/threefoldtech/0-stor_v2/issues/52)
- [ ] ~~optional- escalation to user when issue (telegram? or email?)​​​​ [0-storv2 #53](https://github.com/threefoldtech/0-stor_v2/issues/53)~~

**Comment by LeeSmet** [comment]
For now alerts can be configured by the user in grafana if this is needed
